name: clang-tidy check
on: [push, pull_request]
jobs:
  clang-tidy:
    name: clang-tidy check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: mkdir build && cd build && cmake .. && make clang-tidy
